// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: winter/v1/queue.proto

package winterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnqueueRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Payload        []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Queue          string                 `protobuf:"bytes,3,opt,name=queue,proto3" json:"queue,omitempty"`
	Priority       int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	ScheduledAt    int64                  `protobuf:"varint,5,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	MaxRetries     int32                  `protobuf:"varint,6,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	UniquePeriodMs int64                  `protobuf:"varint,7,opt,name=unique_period_ms,json=uniquePeriodMs,proto3" json:"unique_period_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnqueueRequest) Reset() {
	*x = EnqueueRequest{}
	mi := &file_winter_v1_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRequest) ProtoMessage() {}

func (x *EnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_winter_v1_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRequest.ProtoReflect.Descriptor instead.
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return file_winter_v1_queue_proto_rawDescGZIP(), []int{0}
}

func (x *EnqueueRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *EnqueueRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EnqueueRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *EnqueueRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *EnqueueRequest) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

func (x *EnqueueRequest) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *EnqueueRequest) GetUniquePeriodMs() int64 {
	if x != nil {
		return x.UniquePeriodMs
	}
	return 0
}

type EnqueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueResponse) Reset() {
	*x = EnqueueResponse{}
	mi := &file_winter_v1_queue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueResponse) ProtoMessage() {}

func (x *EnqueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_winter_v1_queue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueResponse.ProtoReflect.Descriptor instead.
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return file_winter_v1_queue_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type DequeueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DequeueRequest) Reset() {
	*x = DequeueRequest{}
	mi := &file_winter_v1_queue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DequeueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueRequest) ProtoMessage() {}

func (x *DequeueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_winter_v1_queue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueRequest.ProtoReflect.Descriptor instead.
func (*DequeueRequest) Descriptor() ([]byte, []int) {
	return file_winter_v1_queue_proto_rawDescGZIP(), []int{2}
}

func (x *DequeueRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *DequeueRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *DequeueRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type DequeueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DequeueResponse) Reset() {
	*x = DequeueResponse{}
	mi := &file_winter_v1_queue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DequeueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueResponse) ProtoMessage() {}

func (x *DequeueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_winter_v1_queue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueResponse.ProtoReflect.Descriptor instead.
func (*DequeueResponse) Descriptor() ([]byte, []int) {
	return file_winter_v1_queue_proto_rawDescGZIP(), []int{3}
}

func (x *DequeueResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_winter_v1_queue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_winter_v1_queue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_winter_v1_queue_proto_rawDescGZIP(), []int{4}
}

func (x *AckRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AckRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *AckRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_winter_v1_queue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_winter_v1_queue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_winter_v1_queue_proto_rawDescGZIP(), []int{5}
}

type NackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	SkipRetry     bool                   `protobuf:"varint,5,opt,name=skip_retry,json=skipRetry,proto3" json:"skip_retry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackRequest) Reset() {
	*x = NackRequest{}
	mi := &file_winter_v1_queue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackRequest) ProtoMessage() {}

func (x *NackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_winter_v1_queue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackRequest.ProtoReflect.Descriptor instead.
func (*NackRequest) Descriptor() ([]byte, []int) {
	return file_winter_v1_queue_proto_rawDescGZIP(), []int{6}
}

func (x *NackRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *NackRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *NackRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *NackRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *NackRequest) GetSkipRetry() bool {
	if x != nil {
		return x.SkipRetry
	}
	return false
}

type NackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outcome       string                 `protobuf:"bytes,1,opt,name=outcome,proto3" json:"outcome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackResponse) Reset() {
	*x = NackResponse{}
	mi := &file_winter_v1_queue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackResponse) ProtoMessage() {}

func (x *NackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_winter_v1_queue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackResponse.ProtoReflect.Descriptor instead.
func (*NackResponse) Descriptor() ([]byte, []int) {
	return file_winter_v1_queue_proto_rawDescGZIP(), []int{7}
}

func (x *NackResponse) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Queues        []string               `protobuf:"bytes,2,rep,name=queues,proto3" json:"queues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_winter_v1_queue_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_winter_v1_queue_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_winter_v1_queue_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetQueues() []string {
	if x != nil {
		return x.Queues
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_winter_v1_queue_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_winter_v1_queue_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_winter_v1_queue_proto_rawDescGZIP(), []int{9}
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_winter_v1_queue_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_winter_v1_queue_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_winter_v1_queue_proto_rawDescGZIP(), []int{10}
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_winter_v1_queue_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_winter_v1_queue_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_winter_v1_queue_proto_rawDescGZIP(), []int{11}
}

func (x *GetJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type QueueStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStatsRequest) Reset() {
	*x = QueueStatsRequest{}
	mi := &file_winter_v1_queue_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatsRequest) ProtoMessage() {}

func (x *QueueStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_winter_v1_queue_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatsRequest.ProtoReflect.Descriptor instead.
func (*QueueStatsRequest) Descriptor() ([]byte, []int) {
	return file_winter_v1_queue_proto_rawDescGZIP(), []int{12}
}

func (x *QueueStatsRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

type QueueStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Ready         int64                  `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	Active        int64                  `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	Delayed       int64                  `protobuf:"varint,4,opt,name=delayed,proto3" json:"delayed,omitempty"`
	Dead          int64                  `protobuf:"varint,5,opt,name=dead,proto3" json:"dead,omitempty"`
	Completed     int64                  `protobuf:"varint,6,opt,name=completed,proto3" json:"completed,omitempty"`
	Failed        int64                  `protobuf:"varint,7,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStatsResponse) Reset() {
	*x = QueueStatsResponse{}
	mi := &file_winter_v1_queue_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatsResponse) ProtoMessage() {}

func (x *QueueStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_winter_v1_queue_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatsResponse.ProtoReflect.Descriptor instead.
func (*QueueStatsResponse) Descriptor() ([]byte, []int) {
	return file_winter_v1_queue_proto_rawDescGZIP(), []int{13}
}

func (x *QueueStatsResponse) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *QueueStatsResponse) GetReady() int64 {
	if x != nil {
		return x.Ready
	}
	return 0
}

func (x *QueueStatsResponse) GetActive() int64 {
	if x != nil {
		return x.Active
	}
	return 0
}

func (x *QueueStatsResponse) GetDelayed() int64 {
	if x != nil {
		return x.Delayed
	}
	return 0
}

func (x *QueueStatsResponse) GetDead() int64 {
	if x != nil {
		return x.Dead
	}
	return 0
}

func (x *QueueStatsResponse) GetCompleted() int64 {
	if x != nil {
		return x.Completed
	}
	return 0
}

func (x *QueueStatsResponse) GetFailed() int64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Queue         string                 `protobuf:"bytes,4,opt,name=queue,proto3" json:"queue,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	State         string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	Attempt       int32                  `protobuf:"varint,7,opt,name=attempt,proto3" json:"attempt,omitempty"`
	MaxRetries    int32                  `protobuf:"varint,8,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ScheduledAt   int64                  `protobuf:"varint,10,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	StartedAt     int64                  `protobuf:"varint,11,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   int64                  `protobuf:"varint,12,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	LastError     string                 `protobuf:"bytes,13,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_winter_v1_queue_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_winter_v1_queue_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_winter_v1_queue_proto_rawDescGZIP(), []int{14}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Job) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Job) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *Job) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Job) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Job) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Job) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *Job) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Job) GetScheduledAt() int64 {
	if x != nil {
		return x.ScheduledAt
	}
	return 0
}

func (x *Job) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *Job) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

func (x *Job) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

var File_winter_v1_queue_proto protoreflect.FileDescriptor

const file_winter_v1_queue_proto_rawDesc = "" +
	"\n" +
	"\x15winter/v1/queue.proto\x12\twinter.v1\"\xde\x01\n" +
	"\x0eEnqueueRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x14\n" +
	"\x05queue\x18\x03 \x01(\tR\x05queue\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12!\n" +
	"\fscheduled_at\x18\x05 \x01(\x03R\vscheduledAt\x12\x1f\n" +
	"\vmax_retries\x18\x06 \x01(\x05R\n" +
	"maxRetries\x12(\n" +
	"\x10unique_period_ms\x18\a \x01(\x03R\x0euniquePeriodMs\"(\n" +
	"\x0fEnqueueResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"b\n" +
	"\x0eDequeueRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x03R\ttimeoutMs\"3\n" +
	"\x0fDequeueResponse\x12 \n" +
	"\x03job\x18\x01 \x01(\v2\x0e.winter.v1.JobR\x03job\"V\n" +
	"\n" +
	"AckRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\"\r\n" +
	"\vAckResponse\"\x8c\x01\n" +
	"\vNackRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"skip_retry\x18\x05 \x01(\bR\tskipRetry\"(\n" +
	"\fNackResponse\x12\x18\n" +
	"\aoutcome\x18\x01 \x01(\tR\aoutcome\"G\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x16\n" +
	"\x06queues\x18\x02 \x03(\tR\x06queues\"\x13\n" +
	"\x11HeartbeatResponse\"&\n" +
	"\rGetJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"2\n" +
	"\x0eGetJobResponse\x12 \n" +
	"\x03job\x18\x01 \x01(\v2\x0e.winter.v1.JobR\x03job\")\n" +
	"\x11QueueStatsRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\"\xbc\x01\n" +
	"\x12QueueStatsResponse\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\x03R\x05ready\x12\x16\n" +
	"\x06active\x18\x03 \x01(\x03R\x06active\x12\x18\n" +
	"\adelayed\x18\x04 \x01(\x03R\adelayed\x12\x12\n" +
	"\x04dead\x18\x05 \x01(\x03R\x04dead\x12\x1c\n" +
	"\tcompleted\x18\x06 \x01(\x03R\tcompleted\x12\x16\n" +
	"\x06failed\x18\a \x01(\x03R\x06failed\"\xe9\x02\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x14\n" +
	"\x05queue\x18\x04 \x01(\tR\x05queue\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12\x18\n" +
	"\aattempt\x18\a \x01(\x05R\aattempt\x12\x1f\n" +
	"\vmax_retries\x18\b \x01(\x05R\n" +
	"maxRetries\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12!\n" +
	"\fscheduled_at\x18\n" +
	" \x01(\x03R\vscheduledAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\v \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\f \x01(\x03R\vcompletedAt\x12\x1d\n" +
	"\n" +
	"last_error\x18\r \x01(\tR\tlastError2\xd3\x03\n" +
	"\fQueueService\x12@\n" +
	"\aEnqueue\x12\x19.winter.v1.EnqueueRequest\x1a\x1a.winter.v1.EnqueueResponse\x12@\n" +
	"\aDequeue\x12\x19.winter.v1.DequeueRequest\x1a\x1a.winter.v1.DequeueResponse\x124\n" +
	"\x03Ack\x12\x15.winter.v1.AckRequest\x1a\x16.winter.v1.AckResponse\x127\n" +
	"\x04Nack\x12\x16.winter.v1.NackRequest\x1a\x17.winter.v1.NackResponse\x12F\n" +
	"\tHeartbeat\x12\x1b.winter.v1.HeartbeatRequest\x1a\x1c.winter.v1.HeartbeatResponse\x12=\n" +
	"\x06GetJob\x12\x18.winter.v1.GetJobRequest\x1a\x19.winter.v1.GetJobResponse\x12I\n" +
	"\n" +
	"QueueStats\x12\x1c.winter.v1.QueueStatsRequest\x1a\x1d.winter.v1.QueueStatsResponseB=Z;github.com/kylegrahammatzen/winter/proto/winter/v1;winterv1b\x06proto3"

var (
	file_winter_v1_queue_proto_rawDescOnce sync.Once
	file_winter_v1_queue_proto_rawDescData []byte
)

func file_winter_v1_queue_proto_rawDescGZIP() []byte {
	file_winter_v1_queue_proto_rawDescOnce.Do(func() {
		file_winter_v1_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_winter_v1_queue_proto_rawDesc), len(file_winter_v1_queue_proto_rawDesc)))
	})
	return file_winter_v1_queue_proto_rawDescData
}

var file_winter_v1_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_winter_v1_queue_proto_goTypes = []any{
	(*EnqueueRequest)(nil),     // 0: winter.v1.EnqueueRequest
	(*EnqueueResponse)(nil),    // 1: winter.v1.EnqueueResponse
	(*DequeueRequest)(nil),     // 2: winter.v1.DequeueRequest
	(*DequeueResponse)(nil),    // 3: winter.v1.DequeueResponse
	(*AckRequest)(nil),         // 4: winter.v1.AckRequest
	(*AckResponse)(nil),        // 5: winter.v1.AckResponse
	(*NackRequest)(nil),        // 6: winter.v1.NackRequest
	(*NackResponse)(nil),       // 7: winter.v1.NackResponse
	(*HeartbeatRequest)(nil),   // 8: winter.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),  // 9: winter.v1.HeartbeatResponse
	(*GetJobRequest)(nil),      // 10: winter.v1.GetJobRequest
	(*GetJobResponse)(nil),     // 11: winter.v1.GetJobResponse
	(*QueueStatsRequest)(nil),  // 12: winter.v1.QueueStatsRequest
	(*QueueStatsResponse)(nil), // 13: winter.v1.QueueStatsResponse
	(*Job)(nil),                // 14: winter.v1.Job
}
var file_winter_v1_queue_proto_depIdxs = []int32{
	14, // 0: winter.v1.DequeueResponse.job:type_name -> winter.v1.Job
	14, // 1: winter.v1.GetJobResponse.job:type_name -> winter.v1.Job
	0,  // 2: winter.v1.QueueService.Enqueue:input_type -> winter.v1.EnqueueRequest
	2,  // 3: winter.v1.QueueService.Dequeue:input_type -> winter.v1.DequeueRequest
	4,  // 4: winter.v1.QueueService.Ack:input_type -> winter.v1.AckRequest
	6,  // 5: winter.v1.QueueService.Nack:input_type -> winter.v1.NackRequest
	8,  // 6: winter.v1.QueueService.Heartbeat:input_type -> winter.v1.HeartbeatRequest
	10, // 7: winter.v1.QueueService.GetJob:input_type -> winter.v1.GetJobRequest
	12, // 8: winter.v1.QueueService.QueueStats:input_type -> winter.v1.QueueStatsRequest
	1,  // 9: winter.v1.QueueService.Enqueue:output_type -> winter.v1.EnqueueResponse
	3,  // 10: winter.v1.QueueService.Dequeue:output_type -> winter.v1.DequeueResponse
	5,  // 11: winter.v1.QueueService.Ack:output_type -> winter.v1.AckResponse
	7,  // 12: winter.v1.QueueService.Nack:output_type -> winter.v1.NackResponse
	9,  // 13: winter.v1.QueueService.Heartbeat:output_type -> winter.v1.HeartbeatResponse
	11, // 14: winter.v1.QueueService.GetJob:output_type -> winter.v1.GetJobResponse
	13, // 15: winter.v1.QueueService.QueueStats:output_type -> winter.v1.QueueStatsResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_winter_v1_queue_proto_init() }
func file_winter_v1_queue_proto_init() {
	if File_winter_v1_queue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_winter_v1_queue_proto_rawDesc), len(file_winter_v1_queue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_winter_v1_queue_proto_goTypes,
		DependencyIndexes: file_winter_v1_queue_proto_depIdxs,
		MessageInfos:      file_winter_v1_queue_proto_msgTypes,
	}.Build()
	File_winter_v1_queue_proto = out.File
	file_winter_v1_queue_proto_goTypes = nil
	file_winter_v1_queue_proto_depIdxs = nil
}
